# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phone_number', models.BigIntegerField(default=0)),
                ('email', models.EmailField(max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('bedroom', models.IntegerField(default=0)),
                ('bathroom', models.IntegerField(default=0)),
                ('coordinate', models.CharField(max_length=500)),
                ('picture', models.FileField(default=None, upload_to='')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10)),
                ('student_type', models.CharField(choices=[('gra', 'graduate'), ('under', 'undergraduate'), ('employed', 'employed')], max_length=50)),
                ('major', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_activate', models.BooleanField(default=True)),
                ('likes', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(default=123, max_length=40)),
                ('key_expires', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
