# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duckmate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='is_favorite',
        ),
    ]
