# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duckmate', '0005_auto_20161129_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='favorite_count',
        ),
    ]
