# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-17 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duckmate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='major',
            field=models.CharField(default='Computer Science', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='student_type',
            field=models.CharField(choices=[('gra', 'graduate'), ('under', 'undergraduate'), ('employed', 'employed')], default='gra', max_length=50),
        ),
    ]
