# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-17 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duckmate', '0003_auto_20161017_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='coordinate',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='picture',
        ),
    ]
