# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-18 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duckmate', '0004_auto_20161017_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
