# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-18 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duckmate', '0005_auto_20161018_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
