# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-19 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duckmate', '0006_auto_20161018_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='pub_date',
        ),
    ]
