# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-19 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duckmate', '0007_auto_20161019_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='picture',
            field=models.FileField(default=None, upload_to=b''),
        ),
    ]
