# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-20 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duckmate', '0008_rental_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='coordinate',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
