# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duckmate', '0010_auto_20161027_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='picture',
            field=models.FileField(default=None, upload_to=b''),
        ),
    ]
